[package]
name = "state_hash_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "state_hash_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }